### PR TITLE
Added confidence scores for each detected object

### PR DESCRIPTION
**Pull request by LeonLok**
Hi Qidian,

I've changed yolo.py and demo.py to show the confidence scores for each detected object at the bottom-left corner of each box. 

I think this would be useful for those who want to show the detection performance of the algorithm.

Thanks,

Leon

### CODE REVIEW

**Comment by LeonLok** [comment]
Thanks for merging, but commit a9afa5f is not needed unless you want to add asynchronous processing. If you do, you also need [videocaptureasync.py](https://github.com/LeonLok/deep_sort_yolov3/blob/master/videocaptureasync.py).

**Comment by LeonLok** [comment]
> 
> 
> ` boxs = yolo.detect_image(image)[0] confidence = yolo.detect_image(image)[1]`
> twice ？

detect_image returns boxes as the first output and scores as the second output.

**Comment by Qidian213** [comment]
why not `boxs , confidence = yolo.detect_image(image) ` ?

**Comment by LeonLok** [comment]
> 
> 
> why not `boxs , confidence = yolo.detect_image(image) ` ?

Ah yes of course! Thanks

**Pull request merged**
